-- Supabase schema for Teens Kingdom Ministry (TKM)
-- Run inside Supabase SQL editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users on delete cascade,
  full_name text,
  department text,
  role text default 'member',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_at timestamptz default now()
);

create table if not exists public.workers (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  bio text,
  photo_url text,
  department_id bigint references public.departments(id),
  created_at timestamptz default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  event_date date,
  location text,
  status text default 'Upcoming',
  created_at timestamptz default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  content text,
  cover_image text,
  published_at timestamptz default now(),
  author_id uuid references auth.users,
  created_at timestamptz default now()
);

create table if not exists public.media (
  id bigint generated by default as identity primary key,
  title text,
  media_type text,
  url text,
  event_id bigint references public.events(id),
  created_at timestamptz default now()
);

create table if not exists public.rankings (
  id bigint generated by default as identity primary key,
  name text not null,
  min_points int,
  max_points int,
  description text
);

create table if not exists public.points_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  activity text,
  points int,
  recorded_at timestamptz default now()
);

create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  full_name text,
  phone text,
  event_name text,
  note text,
  created_at timestamptz default now()
);

create table if not exists public.join_requests (
  id bigint generated by default as identity primary key,
  full_name text,
  age int,
  location text,
  phone text,
  email text,
  department_interest text,
  status text default 'pending',
  created_at timestamptz default now()
);

create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  ministry_name text default 'Teens Kingdom Ministry',
  tagline text default 'Called to Ministry, Empowered by the Gospel',
  logo_url text,
  whatsapp_link text default 'https://chat.whatsapp.com/example',
  updated_at timestamptz default now()
);

-- Helper: create profile rows for new users
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Helper: check admin role
create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- Enable Row Level Security
alter table public.profiles enable row level security;
alter table public.points_history enable row level security;
alter table public.departments enable row level security;
alter table public.workers enable row level security;
alter table public.events enable row level security;
alter table public.posts enable row level security;
alter table public.media enable row level security;
alter table public.rankings enable row level security;
alter table public.rsvps enable row level security;
alter table public.join_requests enable row level security;
alter table public.site_settings enable row level security;

-- Profiles: members can read/update their own profile, admins can manage all
create policy "Profiles are viewable by user" on public.profiles
  for select using (auth.uid() = id or public.is_admin());

create policy "Profiles are editable by user" on public.profiles
  for update using (auth.uid() = id or public.is_admin());

create policy "Profiles are insertable by user" on public.profiles
  for insert with check (auth.uid() = id or public.is_admin());

-- Points history: members can view their own points, admins can manage all
create policy "Points history view" on public.points_history
  for select using (auth.uid() = user_id or public.is_admin());

create policy "Points history insert" on public.points_history
  for insert with check (auth.uid() = user_id or public.is_admin());

create policy "Points history update" on public.points_history
  for update using (public.is_admin());

create policy "Points history delete" on public.points_history
  for delete using (public.is_admin());

-- Admin managed tables
create policy "Departments view" on public.departments
  for select using (true);
create policy "Departments admin" on public.departments
  for all using (public.is_admin()) with check (public.is_admin());

create policy "Workers view" on public.workers
  for select using (true);
create policy "Workers admin" on public.workers
  for all using (public.is_admin()) with check (public.is_admin());

create policy "Events view" on public.events
  for select using (true);
create policy "Events admin" on public.events
  for all using (public.is_admin()) with check (public.is_admin());

create policy "Posts view" on public.posts
  for select using (true);
create policy "Posts admin" on public.posts
  for all using (public.is_admin()) with check (public.is_admin());

create policy "Media view" on public.media
  for select using (true);
create policy "Media admin" on public.media
  for all using (public.is_admin()) with check (public.is_admin());

create policy "Rankings view" on public.rankings
  for select using (true);
create policy "Rankings admin" on public.rankings
  for all using (public.is_admin()) with check (public.is_admin());

-- Public intake tables
create policy "RSVP insert" on public.rsvps
  for insert with check (true);
create policy "RSVP admin" on public.rsvps
  for select using (public.is_admin());
create policy "RSVP delete" on public.rsvps
  for delete using (public.is_admin());

create policy "Join requests insert" on public.join_requests
  for insert with check (true);
create policy "Join requests admin" on public.join_requests
  for select using (public.is_admin());
create policy "Join requests update" on public.join_requests
  for update using (public.is_admin()) with check (public.is_admin());
create policy "Join requests delete" on public.join_requests
  for delete using (public.is_admin());

create policy "Site settings view" on public.site_settings
  for select using (true);
create policy "Site settings admin" on public.site_settings
  for all using (public.is_admin()) with check (public.is_admin());

-- Storage buckets (create in Supabase UI)
-- bucket: media (public or signed URLs)
-- bucket: avatars (public)
