-- Supabase schema for Teens Kingdom Ministry (TKM)
-- Run inside Supabase SQL editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users on delete cascade,
  full_name text,
  department text,
  role text default 'member',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_at timestamptz default now()
);

create table if not exists public.workers (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  bio text,
  photo_url text,
  department_id bigint references public.departments(id),
  created_at timestamptz default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  event_date date,
  location text,
  status text default 'Upcoming',
  created_at timestamptz default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  content text,
  cover_image text,
  published_at timestamptz default now(),
  author_id uuid references auth.users,
  created_at timestamptz default now()
);

create table if not exists public.media (
  id bigint generated by default as identity primary key,
  title text,
  media_type text,
  url text,
  event_id bigint references public.events(id),
  created_at timestamptz default now()
);

create table if not exists public.rankings (
  id bigint generated by default as identity primary key,
  name text not null,
  min_points int,
  max_points int,
  description text
);

create table if not exists public.points_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  activity text,
  points int,
  recorded_at timestamptz default now()
);

create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  full_name text,
  phone text,
  event_name text,
  note text,
  created_at timestamptz default now()
);

create table if not exists public.join_requests (
  id bigint generated by default as identity primary key,
  full_name text,
  age int,
  location text,
  phone text,
  email text,
  department_interest text,
  status text default 'pending',
  created_at timestamptz default now()
);

-- Enable Row Level Security
alter table public.profiles enable row level security;
alter table public.points_history enable row level security;

-- Profiles: members can read/update their own profile
create policy "Profiles are viewable by user" on public.profiles
  for select using (auth.uid() = id);

create policy "Profiles are editable by user" on public.profiles
  for update using (auth.uid() = id);

create policy "Profiles are insertable by user" on public.profiles
  for insert with check (auth.uid() = id);

-- Points history: members can view their own points
create policy "Points history view" on public.points_history
  for select using (auth.uid() = user_id);

create policy "Points history insert" on public.points_history
  for insert with check (auth.uid() = user_id);

-- Admin override: use a role column in profiles for admin access
-- Example: create a helper function or use a separate admin role in JWT claims.

-- Storage buckets (create in Supabase UI)
-- bucket: media (public or signed URLs)
-- bucket: avatars (public)
